
import { Activity } from './types';

export const LANDSCAPES: Activity[] = [
  {
    "id": "L-PDL-100",
    "title": "Lagoa das Sete Cidades (Azul e Verde)",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=100",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+das+Sete+Cidades+(Azul+e+Verde)+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-101",
    "title": "Lagoa do Fogo",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=101",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Fogo+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-102",
    "title": "Lagoa das Furnas",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=102",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+das+Furnas+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-103",
    "title": "Lagoa do Congro",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=103",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Congro+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-104",
    "title": "Lagoa de Santiago",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=104",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+de+Santiago+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-105",
    "title": "Lagoa do Canário",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=105",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Canário+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-106",
    "title": "Lagoa das Éguas",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=106",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+das+Éguas+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-107",
    "title": "Lagoa do Rasa",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=107",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Rasa+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-108",
    "title": "Caldeira Velha",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=108",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Caldeira+Velha+PDL+Azores",
    "isPaid": true,
    "price": 10
  },
  {
    "id": "L-PDL-109",
    "title": "Ponta da Ferraria",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=109",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+da+Ferraria+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-110",
    "title": "Ilhéu de Vila Franca do Campo",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=110",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+de+Vila+Franca+do+Campo+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-111",
    "title": "Salto do Cabrito",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=111",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Salto+do+Cabrito+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-112",
    "title": "Salto do Prego",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=112",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Salto+do+Prego+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-113",
    "title": "Cascata da Ribeira dos Caldeirões",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=113",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Cascata+da+Ribeira+dos+Caldeirões+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-114",
    "title": "Miradouro da Boca do Inferno",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=114",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+da+Boca+do+Inferno+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-115",
    "title": "Miradouro da Vista do Rei",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=115",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+da+Vista+do+Rei+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-116",
    "title": "Miradouro de Santa Iria",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=116",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+de+Santa+Iria+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-117",
    "title": "Miradouro do Pico do Ferro",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=117",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+do+Pico+do+Ferro+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-118",
    "title": "Ermida de Nossa Senhora da Paz",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=118",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ermida+de+Nossa+Senhora+da+Paz+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-119",
    "title": "Plantações de Chá Gorreana e Porto Formoso",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=119",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Plantações+de+Chá+Gorreana+e+Porto+Formoso+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-120",
    "title": "Fumarolas das Furnas",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=120",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fumarolas+das+Furnas+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-121",
    "title": "Poça da Dona Beija",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=121",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Poça+da+Dona+Beija+PDL+Azores",
    "isPaid": true,
    "price": 8
  },
  {
    "id": "L-PDL-122",
    "title": "Parque Terra Nostra",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=122",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Parque+Terra+Nostra+PDL+Azores",
    "isPaid": true,
    "price": 10
  },
  {
    "id": "L-PDL-123",
    "title": "Ilhéu dos Mosteiros",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=123",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+dos+Mosteiros+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-124",
    "title": "Ponta da Madrugada",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=124",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+da+Madrugada+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-125",
    "title": "Ponta do Sossego",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=125",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+do+Sossego+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-126",
    "title": "Salto da Farinha",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=126",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Salto+da+Farinha+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PDL-127",
    "title": "Grota do Inferno",
    "type": "landscape",
    "island": "PDL",
    "image": "https://picsum.photos/400/300?random=127",
    "description": "Uma das paisagens mais emblemáticas da ilha de PDL, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Grota+do+Inferno+PDL+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-128",
    "title": "Barreiro da Faneca (Deserto Vermelho)",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=128",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Barreiro+da+Faneca+(Deserto+Vermelho)+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-129",
    "title": "Baía de São Lourenço",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=129",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Baía+de+São+Lourenço+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-130",
    "title": "Baía dos Anjos",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=130",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Baía+dos+Anjos+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-131",
    "title": "Cascata do Aveiro",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=131",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Cascata+do+Aveiro+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-132",
    "title": "Poço da Rocha",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=132",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Poço+da+Rocha+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-133",
    "title": "Pico Alto",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=133",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Pico+Alto+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-134",
    "title": "Ribeira de Maloás (Colunas Basálticas)",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=134",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ribeira+de+Maloás+(Colunas+Basálticas)+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-135",
    "title": "Praia Formosa",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=135",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Praia+Formosa+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-136",
    "title": "Ilhéu da Vila",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=136",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+da+Vila+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-137",
    "title": "Ponta do Castelo",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=137",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+do+Castelo+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SMA-138",
    "title": "Farol de Gonçalo Velho",
    "type": "landscape",
    "island": "SMA",
    "image": "https://picsum.photos/400/300?random=138",
    "description": "Uma das paisagens mais emblemáticas da ilha de SMA, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Farol+de+Gonçalo+Velho+SMA+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-139",
    "title": "Algar do Carvão",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=139",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Algar+do+Carvão+TER+Azores",
    "isPaid": true,
    "price": 10
  },
  {
    "id": "L-TER-140",
    "title": "Gruta do Natal",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=140",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Gruta+do+Natal+TER+Azores",
    "isPaid": true,
    "price": 8
  },
  {
    "id": "L-TER-141",
    "title": "Furnas do Enxofre",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=141",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Furnas+do+Enxofre+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-142",
    "title": "Serra do Cume (Manto de Retalhos)",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=142",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Serra+do+Cume+(Manto+de+Retalhos)+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-143",
    "title": "Monte Brasil",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=143",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Monte+Brasil+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-144",
    "title": "Piscinas Naturais de Biscoitos",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=144",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Piscinas+Naturais+de+Biscoitos+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-145",
    "title": "Lagoa das Patas (Falca)",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=145",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+das+Patas+(Falca)+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-146",
    "title": "Baía de Angra do Heroísmo",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=146",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Baía+de+Angra+do+Heroísmo+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-147",
    "title": "Ponta das Contendas",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=147",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+das+Contendas+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-148",
    "title": "Ilhéu das Cabras",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=148",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+das+Cabras+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-149",
    "title": "Miradouro do Facho",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=149",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+do+Facho+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-150",
    "title": "Serra de Santa Bárbara",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=150",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Serra+de+Santa+Bárbara+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-151",
    "title": "Mistérios Negros",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=151",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Mistérios+Negros+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-TER-152",
    "title": "Rocha do Chambre",
    "type": "landscape",
    "island": "TER",
    "image": "https://picsum.photos/400/300?random=152",
    "description": "Uma das paisagens mais emblemáticas da ilha de TER, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Rocha+do+Chambre+TER+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-153",
    "title": "Montanha do Pico (Piquinho)",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=153",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Montanha+do+Pico+(Piquinho)+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-154",
    "title": "Criação Velha (Vinhas UNESCO)",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=154",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Criação+Velha+(Vinhas+UNESCO)+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-155",
    "title": "Lajido da Criação Velha",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=155",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lajido+da+Criação+Velha+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-156",
    "title": "Lagoa do Capitão",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=156",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Capitão+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-157",
    "title": "Lagoa do Caiado",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=157",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Caiado+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-158",
    "title": "Lagoa do Peixinho",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=158",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Peixinho+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-159",
    "title": "Lagoa de São Roque",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=159",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+de+São+Roque+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-160",
    "title": "Lagoa do Rosada",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=160",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+do+Rosada+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-161",
    "title": "Gruta das Torres",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=161",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Gruta+das+Torres+PIX+Azores",
    "isPaid": true,
    "price": 8
  },
  {
    "id": "L-PIX-162",
    "title": "Mistérios de São João",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=162",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Mistérios+de+São+João+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-163",
    "title": "Mistérios de Santa Luzia",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=163",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Mistérios+de+Santa+Luzia+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-164",
    "title": "Ponta da Ilha",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=164",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+da+Ilha+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-165",
    "title": "Cais do Pico",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=165",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Cais+do+Pico+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-166",
    "title": "Arcos do Cachorro",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=166",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Arcos+do+Cachorro+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-PIX-167",
    "title": "Buraca de Ascensão",
    "type": "landscape",
    "island": "PIX",
    "image": "https://picsum.photos/400/300?random=167",
    "description": "Uma das paisagens mais emblemáticas da ilha de PIX, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Buraca+de+Ascensão+PIX+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-168",
    "title": "Vulcão dos Capelinhos",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=168",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Vulcão+dos+Capelinhos+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-169",
    "title": "Caldeira do Faial",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=169",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Caldeira+do+Faial+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-170",
    "title": "Monte da Guia",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=170",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Monte+da+Guia+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-171",
    "title": "Praia do Almoxarife",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=171",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Praia+do+Almoxarife+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-172",
    "title": "Praia de Porto Pim",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=172",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Praia+de+Porto+Pim+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-173",
    "title": "Varadouro (Piscinas Naturais)",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=173",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Varadouro+(Piscinas+Naturais)+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-174",
    "title": "Morro de Castelo Branco",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=174",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Morro+de+Castelo+Branco+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-175",
    "title": "Miradouro de Nossa Senhora da Conceição",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=175",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+de+Nossa+Senhora+da+Conceição+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-176",
    "title": "Ribeirinha (Ruínas do Sismo)",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=176",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ribeirinha+(Ruínas+do+Sismo)+HOR+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-HOR-177",
    "title": "Jardim Botânico do Faial",
    "type": "landscape",
    "island": "HOR",
    "image": "https://picsum.photos/400/300?random=177",
    "description": "Uma das paisagens mais emblemáticas da ilha de HOR, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Jardim+Botânico+do+Faial+HOR+Azores",
    "isPaid": true,
    "price": 5
  },
  {
    "id": "L-SJZ-178",
    "title": "Fajã de Santo Cristo",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=178",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+de+Santo+Cristo+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-179",
    "title": "Fajã dos Cubres",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=179",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+dos+Cubres+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-180",
    "title": "Fajã do Ouvidor (Piscina Natural Simão Dias)",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=180",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+do+Ouvidor+(Piscina+Natural+Simão+Dias)+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-181",
    "title": "Fajã de São João",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=181",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+de+São+João+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-182",
    "title": "Fajã dos Vimes",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=182",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+dos+Vimes+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-183",
    "title": "Pico da Esperança",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=183",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Pico+da+Esperança+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-184",
    "title": "Ponta dos Rosais (Farol)",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=184",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+dos+Rosais+(Farol)+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-185",
    "title": "Ponta do Topo e Ilhéu do Topo",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=185",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+do+Topo+e+Ilhéu+do+Topo+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-186",
    "title": "Cascata do Cruzal",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=186",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Cascata+do+Cruzal+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-SJZ-187",
    "title": "Ribeira do Nabo",
    "type": "landscape",
    "island": "SJZ",
    "image": "https://picsum.photos/400/300?random=187",
    "description": "Uma das paisagens mais emblemáticas da ilha de SJZ, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ribeira+do+Nabo+SJZ+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-188",
    "title": "Furna do Enxofre",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=188",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Furna+do+Enxofre+GRW+Azores",
    "isPaid": true,
    "price": 5
  },
  {
    "id": "L-GRW-189",
    "title": "Caldeira da Graciosa",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=189",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Caldeira+da+Graciosa+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-190",
    "title": "Carapacho (Termas e Piscinas)",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=190",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Carapacho+(Termas+e+Piscinas)+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-191",
    "title": "Ilhéu da Praia",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=191",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+da+Praia+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-192",
    "title": "Ilhéu de Baixo",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=192",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+de+Baixo+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-193",
    "title": "Ponta da Barca (Farol)",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=193",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+da+Barca+(Farol)+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-194",
    "title": "Ponta da Restinga",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=194",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+da+Restinga+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-195",
    "title": "Moinhos de Vento Vermelhos",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=195",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Moinhos+de+Vento+Vermelhos+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-GRW-196",
    "title": "Monte de Nossa Senhora da Ajuda",
    "type": "landscape",
    "island": "GRW",
    "image": "https://picsum.photos/400/300?random=196",
    "description": "Uma das paisagens mais emblemáticas da ilha de GRW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Monte+de+Nossa+Senhora+da+Ajuda+GRW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-197",
    "title": "Poço da Alagoinha (Lagoa das Patas)",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=197",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Poço+da+Alagoinha+(Lagoa+das+Patas)+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-198",
    "title": "Rocha dos Bordões",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=198",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Rocha+dos+Bordões+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-199",
    "title": "Cascata do Poço do Bacalhau",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=199",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Cascata+do+Poço+do+Bacalhau+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-200",
    "title": "Lagoa Negra",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=200",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Negra+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-201",
    "title": "Lagoa Comprida",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=201",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Comprida+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-202",
    "title": "Lagoa Rasa",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=202",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Rasa+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-203",
    "title": "Lagoa Funda",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=203",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Funda+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-204",
    "title": "Lagoa da Lomba",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=204",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+da+Lomba+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-205",
    "title": "Lagoa Branca",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=205",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Branca+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-206",
    "title": "Lagoa Seca",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=206",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoa+Seca+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-207",
    "title": "Fajã Grande",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=207",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajã+Grande+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-208",
    "title": "Fajãzinha",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=208",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Fajãzinha+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-209",
    "title": "Ilhéu de Monchique (Ponto mais a Oeste da Europa)",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=209",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ilhéu+de+Monchique+(Ponto+mais+a+Oeste+da+Europa)+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-FLW-210",
    "title": "Gruta dos Enxaréus",
    "type": "landscape",
    "island": "FLW",
    "image": "https://picsum.photos/400/300?random=210",
    "description": "Uma das paisagens mais emblemáticas da ilha de FLW, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Gruta+dos+Enxaréus+FLW+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-211",
    "title": "Caldeirão do Corvo",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=211",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Caldeirão+do+Corvo+CVU+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-212",
    "title": "Lagoas do Caldeirão",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=212",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Lagoas+do+Caldeirão+CVU+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-213",
    "title": "Vila do Corvo",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=213",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Vila+do+Corvo+CVU+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-214",
    "title": "Ponta do Marco",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=214",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Ponta+do+Marco+CVU+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-215",
    "title": "Morro dos Homens",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=215",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Morro+dos+Homens+CVU+Azores",
    "isPaid": false,
    "price": 0
  },
  {
    "id": "L-CVU-216",
    "title": "Miradouro do Pão de Açúcar",
    "type": "landscape",
    "island": "CVU",
    "image": "https://picsum.photos/400/300?random=216",
    "description": "Uma das paisagens mais emblemáticas da ilha de CVU, oferecendo vistas deslumbrantes e uma conexão única com a natureza açoriana.",
    "mapUrl": "https://www.google.com/maps/search/?api=1&query=Miradouro+do+Pão+de+Açúcar+CVU+Azores",
    "isPaid": false,
    "price": 0
  }
];
