// AUTO-GENERATED by generate_bus_network.cjs — real bus stops from OpenStreetMap (Overpass API).
// Re-run the script to refresh. Do not hand-edit generated entries; add manual ones separately.
import { BusStop } from '../types';

export const realBusStops: BusStop[] = [
  {
    "id": "osm_289359902",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7423024,
    "lng": -25.663724
  },
  {
    "id": "osm_292278352",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.750191,
    "lng": -25.6319208
  },
  {
    "id": "osm_380690710",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8120641,
    "lng": -25.5741307
  },
  {
    "id": "osm_380789429",
    "name": "Paragem – Sete Cidades",
    "lat": 37.854432,
    "lng": -25.7944695
  },
  {
    "id": "osm_383483866",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8044535,
    "lng": -25.6738538
  },
  {
    "id": "osm_695233866",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7602886,
    "lng": -25.6040672
  },
  {
    "id": "osm_759528184",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7385785,
    "lng": -25.6701692
  },
  {
    "id": "osm_759568493",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7383924,
    "lng": -25.6692081
  },
  {
    "id": "osm_760597365",
    "name": "Rua São João",
    "lat": 37.7420716,
    "lng": -25.665602
  },
  {
    "id": "osm_762116352",
    "name": "Paragem – Furnas",
    "lat": 37.7732631,
    "lng": -25.3160775
  },
  {
    "id": "osm_764446611",
    "name": "17 Rua Jose do Canto Escola das Anexas",
    "lat": 37.7466455,
    "lng": -25.6691936
  },
  {
    "id": "osm_764537966",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7377181,
    "lng": -25.6701414
  },
  {
    "id": "osm_764538013",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7376383,
    "lng": -25.6703902
  },
  {
    "id": "osm_764538656",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7371209,
    "lng": -25.6725798
  },
  {
    "id": "osm_765057154",
    "name": "Rua Dr. José Bruno Tavares Carreiro",
    "lat": 37.7404069,
    "lng": -25.6654856
  },
  {
    "id": "osm_1068879050",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7170834,
    "lng": -25.4318478
  },
  {
    "id": "osm_1113339172",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7159742,
    "lng": -25.4397628
  },
  {
    "id": "osm_1174906925",
    "name": "Paragem – Ramal Mosteiros",
    "lat": 37.8669993,
    "lng": -25.8330829
  },
  {
    "id": "osm_1186459363",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8212075,
    "lng": -25.6087302
  },
  {
    "id": "osm_1186566894",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8279813,
    "lng": -25.6412142
  },
  {
    "id": "osm_1264873353",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7337727,
    "lng": -25.6863996
  },
  {
    "id": "osm_1368545861",
    "name": "Paragem – Fajã de Baixo",
    "lat": 37.75249,
    "lng": -25.6514154
  },
  {
    "id": "osm_1386402553",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7453495,
    "lng": -25.6762538
  },
  {
    "id": "osm_1386402555",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7453978,
    "lng": -25.6762448
  },
  {
    "id": "osm_1427546397",
    "name": "Paragem – Furnas",
    "lat": 37.7705918,
    "lng": -25.2951505
  },
  {
    "id": "osm_1427546440",
    "name": "Paragem – Furnas",
    "lat": 37.7713386,
    "lng": -25.3032896
  },
  {
    "id": "osm_1427546559",
    "name": "Rede Geral",
    "lat": 37.7728786,
    "lng": -25.3044443
  },
  {
    "id": "osm_1436387865",
    "name": "Paragem – Santo António",
    "lat": 37.8616756,
    "lng": -25.7071056
  },
  {
    "id": "osm_1788317274",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8022308,
    "lng": -25.6119402
  },
  {
    "id": "osm_1788451443",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8283697,
    "lng": -25.6465554
  },
  {
    "id": "osm_1806186102",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7520351,
    "lng": -25.6739988
  },
  {
    "id": "osm_1927342346",
    "name": "Paragem – Povoação",
    "lat": 37.7669457,
    "lng": -25.2284394
  },
  {
    "id": "osm_1927342398",
    "name": "Paragem – Povoação",
    "lat": 37.7604753,
    "lng": -25.2343996
  },
  {
    "id": "osm_1938246424",
    "name": "Paragem – Capelas",
    "lat": 37.8362355,
    "lng": -25.6928948
  },
  {
    "id": "osm_1938246437",
    "name": "Paragem – Capelas",
    "lat": 37.8382702,
    "lng": -25.6883053
  },
  {
    "id": "osm_1938246457",
    "name": "Paragem – Capelas",
    "lat": 37.8393778,
    "lng": -25.6938267
  },
  {
    "id": "osm_1944753792",
    "name": "Atalhada - Modelo",
    "lat": 37.7450437,
    "lng": -25.586218
  },
  {
    "id": "osm_1948125035",
    "name": "Paragem – Maia",
    "lat": 37.8202305,
    "lng": -25.4136677
  },
  {
    "id": "osm_1950017870",
    "name": "Paragem – Furnas",
    "lat": 37.7361499,
    "lng": -25.29907
  },
  {
    "id": "osm_1955172189",
    "name": "Furnas",
    "lat": 37.7725509,
    "lng": -25.3160727
  },
  {
    "id": "osm_2271881518",
    "name": "C.M. Nordeste Paragem Vila do Nordeste",
    "lat": 37.8318168,
    "lng": -25.1453438
  },
  {
    "id": "osm_2292248983",
    "name": "Ribeirinha",
    "lat": 37.8266502,
    "lng": -25.5009034
  },
  {
    "id": "osm_2292261715",
    "name": "Paragem de Autocarro",
    "lat": 37.8523229,
    "lng": -25.2089223
  },
  {
    "id": "osm_2292270571",
    "name": "Estação da Ribeira Grande",
    "lat": 37.8223297,
    "lng": -25.5232617
  },
  {
    "id": "osm_2400284350",
    "name": "Paragem de Autocarro",
    "lat": 37.84876,
    "lng": -25.233131
  },
  {
    "id": "osm_2427047625",
    "name": "Ginetes",
    "lat": 37.8480083,
    "lng": -25.838779
  },
  {
    "id": "osm_2497788241",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8144005,
    "lng": -25.5884489
  },
  {
    "id": "osm_2850290058",
    "name": "Paragem – Maia",
    "lat": 37.816801,
    "lng": -25.4022487
  },
  {
    "id": "osm_3397636301",
    "name": "Paragem – Sete Cidades",
    "lat": 37.858703,
    "lng": -25.7966663
  },
  {
    "id": "osm_3761891667",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7193845,
    "lng": -25.4552966
  },
  {
    "id": "osm_3761891698",
    "name": "Paragem – Povoação",
    "lat": 37.763629,
    "lng": -25.2315053
  },
  {
    "id": "osm_3761891703",
    "name": "Terminal de Autocarros",
    "lat": 37.7724762,
    "lng": -25.3107871
  },
  {
    "id": "osm_3856544668",
    "name": "Paragem – Capelas",
    "lat": 37.831573,
    "lng": -25.687051
  },
  {
    "id": "osm_3856797394",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7589534,
    "lng": -25.6053373
  },
  {
    "id": "osm_3856797441",
    "name": "Paragem – Capelas",
    "lat": 37.8296962,
    "lng": -25.6670299
  },
  {
    "id": "osm_3856797444",
    "name": "Paragem – Capelas",
    "lat": 37.8329492,
    "lng": -25.6890731
  },
  {
    "id": "osm_3856797445",
    "name": "Paragem – Santo António",
    "lat": 37.8534706,
    "lng": -25.7031953
  },
  {
    "id": "osm_3856797446",
    "name": "Paragem – Santo António",
    "lat": 37.8669817,
    "lng": -25.7096367
  },
  {
    "id": "osm_3856797447",
    "name": "Paragem – Santo António",
    "lat": 37.8696842,
    "lng": -25.7135803
  },
  {
    "id": "osm_3856932305",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8195411,
    "lng": -25.6036974
  },
  {
    "id": "osm_3856976183",
    "name": "Paragem – Capelas",
    "lat": 37.8190345,
    "lng": -25.6703894
  },
  {
    "id": "osm_3857340283",
    "name": "Paragem – Povoação",
    "lat": 37.7422187,
    "lng": -25.1960066
  },
  {
    "id": "osm_4337635299",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7482126,
    "lng": -25.6763168
  },
  {
    "id": "osm_4337701803",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7603375,
    "lng": -25.7034236
  },
  {
    "id": "osm_4337702391",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7612188,
    "lng": -25.7038714
  },
  {
    "id": "osm_4337741096",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.764858,
    "lng": -25.7048362
  },
  {
    "id": "osm_4341809289",
    "name": "Rua da Juventude",
    "lat": 37.7461735,
    "lng": -25.6757261
  },
  {
    "id": "osm_4341887789",
    "name": "Paragem de Autocarro",
    "lat": 37.8509805,
    "lng": -25.2051248
  },
  {
    "id": "osm_4341887889",
    "name": "Paragem de Autocarro",
    "lat": 37.8530943,
    "lng": -25.212906
  },
  {
    "id": "osm_4471585231",
    "name": "Lagoa - Casa Batista",
    "lat": 37.7459502,
    "lng": -25.5761244
  },
  {
    "id": "osm_4796851552",
    "name": "Linha Azul",
    "lat": 37.740631,
    "lng": -25.6699345
  },
  {
    "id": "osm_4796851554",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7416305,
    "lng": -25.6682012
  },
  {
    "id": "osm_4798360515",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7550617,
    "lng": -25.6973326
  },
  {
    "id": "osm_4798360516",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7538826,
    "lng": -25.6945552
  },
  {
    "id": "osm_4798377129",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7756417,
    "lng": -25.7077519
  },
  {
    "id": "osm_4798739840",
    "name": "Paragem – Santo António",
    "lat": 37.8546912,
    "lng": -25.705035
  },
  {
    "id": "osm_4798739850",
    "name": "Paragem – Santo António",
    "lat": 37.8602846,
    "lng": -25.7068053
  },
  {
    "id": "osm_4798785697",
    "name": "Paragem – Santo António",
    "lat": 37.8593544,
    "lng": -25.7030931
  },
  {
    "id": "osm_4798817682",
    "name": "Paragem – Santo António",
    "lat": 37.869466,
    "lng": -25.7101327
  },
  {
    "id": "osm_4798844883",
    "name": "Paragem – Santo António",
    "lat": 37.8736418,
    "lng": -25.7178059
  },
  {
    "id": "osm_4798867635",
    "name": "Paragem – Santo António",
    "lat": 37.8770479,
    "lng": -25.7246322
  },
  {
    "id": "osm_4798867636",
    "name": "Paragem – Santo António",
    "lat": 37.8769992,
    "lng": -25.7245195
  },
  {
    "id": "osm_4802436295",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8568221,
    "lng": -25.7905434
  },
  {
    "id": "osm_4802436316",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8615461,
    "lng": -25.7932457
  },
  {
    "id": "osm_4803339559",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8609812,
    "lng": -25.7938975
  },
  {
    "id": "osm_4803339561",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8610002,
    "lng": -25.7947706
  },
  {
    "id": "osm_4803349543",
    "name": "Vareza",
    "lat": 37.8663889,
    "lng": -25.8342064
  },
  {
    "id": "osm_4803382424",
    "name": "Paragem – Ramal Mosteiros",
    "lat": 37.8547431,
    "lng": -25.8418632
  },
  {
    "id": "osm_4803417554",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8419022,
    "lng": -25.8339228
  },
  {
    "id": "osm_4803417575",
    "name": "Paragem – Ramal Mosteiros",
    "lat": 37.8454193,
    "lng": -25.8364642
  },
  {
    "id": "osm_4803509179",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8212928,
    "lng": -25.8188958
  },
  {
    "id": "osm_4803509184",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8233467,
    "lng": -25.8215928
  },
  {
    "id": "osm_4803509189",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8292078,
    "lng": -25.8291312
  },
  {
    "id": "osm_4803509192",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8311105,
    "lng": -25.8314592
  },
  {
    "id": "osm_4804149275",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7533043,
    "lng": -25.7157538
  },
  {
    "id": "osm_4804149277",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7556657,
    "lng": -25.7199233
  },
  {
    "id": "osm_4804149281",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7593714,
    "lng": -25.725336
  },
  {
    "id": "osm_4804171199",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.743905,
    "lng": -25.6957209
  },
  {
    "id": "osm_4804229122",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7396573,
    "lng": -25.6858592
  },
  {
    "id": "osm_4804662652",
    "name": "São Roque - Torreão",
    "lat": 37.7456942,
    "lng": -25.642063
  },
  {
    "id": "osm_4804685557",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.742463,
    "lng": -25.6768794
  },
  {
    "id": "osm_4809471423",
    "name": "Paragem – Maia",
    "lat": 37.8275418,
    "lng": -25.399986
  },
  {
    "id": "osm_4809646935",
    "name": "Paragem – Maia",
    "lat": 37.8298615,
    "lng": -25.3758359
  },
  {
    "id": "osm_4809873564",
    "name": "Paragem – Maia",
    "lat": 37.8169789,
    "lng": -25.4021421
  },
  {
    "id": "osm_4812178858",
    "name": "Paragem – Ribeira Grande",
    "lat": 37.8238279,
    "lng": -25.5203625
  },
  {
    "id": "osm_4812178870",
    "name": "Paragem – Ribeira Grande",
    "lat": 37.8249508,
    "lng": -25.5147815
  },
  {
    "id": "osm_4812263573",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8215651,
    "lng": -25.5265322
  },
  {
    "id": "osm_4812855314",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8199866,
    "lng": -25.5298005
  },
  {
    "id": "osm_4813200593",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8187447,
    "lng": -25.5347468
  },
  {
    "id": "osm_4813680281",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.741465,
    "lng": -25.6561815
  },
  {
    "id": "osm_4857662021",
    "name": "Chá Gorreana",
    "lat": 37.8208234,
    "lng": -25.4096284
  },
  {
    "id": "osm_4864030721",
    "name": "Paragem – Furnas",
    "lat": 37.7644354,
    "lng": -25.3273457
  },
  {
    "id": "osm_4866521122",
    "name": "Ponta Delgada / São Pedro / Rua do Clerigos",
    "lat": 37.7408493,
    "lng": -25.6627819
  },
  {
    "id": "osm_4931193022",
    "name": "Avenida Marginal",
    "lat": 37.739784,
    "lng": -25.6663242
  },
  {
    "id": "osm_4931231021",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7408577,
    "lng": -25.6628094
  },
  {
    "id": "osm_4931231022",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7425108,
    "lng": -25.6547607
  },
  {
    "id": "osm_4931231221",
    "name": "Ponta Delgada / Rua Eng. José Cordeiro",
    "lat": 37.7425723,
    "lng": -25.6582591
  },
  {
    "id": "osm_4931255828",
    "name": "Paragem – Fajã de Baixo",
    "lat": 37.7582404,
    "lng": -25.6465194
  },
  {
    "id": "osm_4931255829",
    "name": "Paragem – Fajã de Baixo",
    "lat": 37.7598251,
    "lng": -25.643522
  },
  {
    "id": "osm_4931261723",
    "name": "Paragem – Fajã de Baixo",
    "lat": 37.7570362,
    "lng": -25.6490341
  },
  {
    "id": "osm_4986621761",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7163403,
    "lng": -25.4656183
  },
  {
    "id": "osm_4986621762",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7163095,
    "lng": -25.4654413
  },
  {
    "id": "osm_5050573021",
    "name": "Maia",
    "lat": 37.8308479,
    "lng": -25.38879
  },
  {
    "id": "osm_5088465822",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7165749,
    "lng": -25.3705559
  },
  {
    "id": "osm_5088465823",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8631459,
    "lng": -25.7962377
  },
  {
    "id": "osm_5092469022",
    "name": "Paragem – Maia",
    "lat": 37.8298724,
    "lng": -25.3912951
  },
  {
    "id": "osm_5092469023",
    "name": "Paragem – Maia",
    "lat": 37.8300728,
    "lng": -25.3732146
  },
  {
    "id": "osm_5092469024",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8494688,
    "lng": -25.3226558
  },
  {
    "id": "osm_5092469025",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8501725,
    "lng": -25.3000006
  },
  {
    "id": "osm_5092469026",
    "name": "Paragem de Autocarro",
    "lat": 37.8508543,
    "lng": -25.2478147
  },
  {
    "id": "osm_5092472622",
    "name": "Paragem – Maia",
    "lat": 37.8292961,
    "lng": -25.3617933
  },
  {
    "id": "osm_5092472623",
    "name": "Paragem – Maia",
    "lat": 37.8294229,
    "lng": -25.3567463
  },
  {
    "id": "osm_5092472624",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8303516,
    "lng": -25.3527638
  },
  {
    "id": "osm_5092472625",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8365988,
    "lng": -25.3423418
  },
  {
    "id": "osm_5092472626",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8519161,
    "lng": -25.3237997
  },
  {
    "id": "osm_5092472627",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8497658,
    "lng": -25.3119885
  },
  {
    "id": "osm_5092472628",
    "name": "Paragem de Autocarro",
    "lat": 37.8504409,
    "lng": -25.284587
  },
  {
    "id": "osm_5092476921",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8351241,
    "lng": -25.3459086
  },
  {
    "id": "osm_5092477021",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8472392,
    "lng": -25.3163021
  },
  {
    "id": "osm_5092477022",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8496259,
    "lng": -25.3086585
  },
  {
    "id": "osm_5092477023",
    "name": "Paragem de Autocarro",
    "lat": 37.8500365,
    "lng": -25.2568876
  },
  {
    "id": "osm_5092477024",
    "name": "Paragem de Autocarro",
    "lat": 37.8512686,
    "lng": -25.2498811
  },
  {
    "id": "osm_5092477026",
    "name": "Paragem de Autocarro",
    "lat": 37.8489074,
    "lng": -25.2281052
  },
  {
    "id": "osm_5092477027",
    "name": "Paragem de Autocarro",
    "lat": 37.8493789,
    "lng": -25.1938113
  },
  {
    "id": "osm_5092477028",
    "name": "Paragem de Autocarro",
    "lat": 37.8509331,
    "lng": -25.1792214
  },
  {
    "id": "osm_5092477029",
    "name": "Paragem de Autocarro",
    "lat": 37.8502809,
    "lng": -25.1724134
  },
  {
    "id": "osm_5092477031",
    "name": "Paragem de Autocarro",
    "lat": 37.8415545,
    "lng": -25.1555163
  },
  {
    "id": "osm_5092477921",
    "name": "Paragem de Autocarro",
    "lat": 37.8544305,
    "lng": -25.2164652
  },
  {
    "id": "osm_5095285526",
    "name": "Paragem de Autocarro",
    "lat": 37.8255372,
    "lng": -25.1429804
  },
  {
    "id": "osm_5102877521",
    "name": "Paragem – Maia",
    "lat": 37.829319,
    "lng": -25.3939243
  },
  {
    "id": "osm_5120001187",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8504256,
    "lng": -25.2999431
  },
  {
    "id": "osm_5120029954",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8475209,
    "lng": -25.3003545
  },
  {
    "id": "osm_5120045511",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8441131,
    "lng": -25.2996565
  },
  {
    "id": "osm_5120075188",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.8424255,
    "lng": -25.2999253
  },
  {
    "id": "osm_5120085056",
    "name": "Paragem – Fenais da Ajuda",
    "lat": 37.84102,
    "lng": -25.3000273
  },
  {
    "id": "osm_5137181920",
    "name": "Paragem de Autocarro",
    "lat": 37.855242,
    "lng": -25.2812888
  },
  {
    "id": "osm_5137189782",
    "name": "Paragem de Autocarro",
    "lat": 37.8533716,
    "lng": -25.2824085
  },
  {
    "id": "osm_5137232232",
    "name": "Paragem de Autocarro",
    "lat": 37.8503216,
    "lng": -25.2845195
  },
  {
    "id": "osm_5137248419",
    "name": "Paragem de Autocarro",
    "lat": 37.8490338,
    "lng": -25.280597
  },
  {
    "id": "osm_5162730527",
    "name": "Paragem de Autocarro",
    "lat": 37.8585867,
    "lng": -25.2642147
  },
  {
    "id": "osm_5162749603",
    "name": "Paragem de Autocarro",
    "lat": 37.8532622,
    "lng": -25.2662297
  },
  {
    "id": "osm_5162755996",
    "name": "Paragem de Autocarro",
    "lat": 37.847322,
    "lng": -25.2653979
  },
  {
    "id": "osm_5183413704",
    "name": "Paragem de Autocarro",
    "lat": 37.8543526,
    "lng": -25.2557604
  },
  {
    "id": "osm_5183442530",
    "name": "Paragem de Autocarro",
    "lat": 37.850017,
    "lng": -25.2555478
  },
  {
    "id": "osm_5183448663",
    "name": "Paragem de Autocarro",
    "lat": 37.8500743,
    "lng": -25.2543123
  },
  {
    "id": "osm_5190699663",
    "name": "Paragem de Autocarro",
    "lat": 37.8450272,
    "lng": -25.2301864
  },
  {
    "id": "osm_5218196326",
    "name": "Paragem de Autocarro",
    "lat": 37.84972,
    "lng": -25.1997741
  },
  {
    "id": "osm_5218221780",
    "name": "Paragem de Autocarro",
    "lat": 37.8495906,
    "lng": -25.1976001
  },
  {
    "id": "osm_5235125195",
    "name": "Paragem de Autocarro",
    "lat": 37.8502448,
    "lng": -25.1731846
  },
  {
    "id": "osm_5235134468",
    "name": "Paragem de Autocarro",
    "lat": 37.8495949,
    "lng": -25.1682989
  },
  {
    "id": "osm_5235146522",
    "name": "Paragem de Autocarro",
    "lat": 37.8471995,
    "lng": -25.1649584
  },
  {
    "id": "osm_5235151457",
    "name": "Paragem de Autocarro",
    "lat": 37.8450719,
    "lng": -25.1617006
  },
  {
    "id": "osm_5235156426",
    "name": "Paragem de Autocarro",
    "lat": 37.8440808,
    "lng": -25.1590936
  },
  {
    "id": "osm_5235161680",
    "name": "Paragem de Autocarro",
    "lat": 37.8426245,
    "lng": -25.156168
  },
  {
    "id": "osm_5239358884",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7467123,
    "lng": -25.6570753
  },
  {
    "id": "osm_5239433435",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7500569,
    "lng": -25.6580369
  },
  {
    "id": "osm_5239433454",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7481874,
    "lng": -25.6572805
  },
  {
    "id": "osm_5242568822",
    "name": "Paragem – Lagoa",
    "lat": 37.7220231,
    "lng": -25.5169795
  },
  {
    "id": "osm_5242807123",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7198347,
    "lng": -25.5067952
  },
  {
    "id": "osm_5248519109",
    "name": "Paragem – Furnas",
    "lat": 37.7701272,
    "lng": -25.3159013
  },
  {
    "id": "osm_5248734242",
    "name": "Paragem – Furnas",
    "lat": 37.7542315,
    "lng": -25.2876976
  },
  {
    "id": "osm_5248804800",
    "name": "Paragem – Povoação",
    "lat": 37.7483751,
    "lng": -25.2657142
  },
  {
    "id": "osm_5249572461",
    "name": "Paragem – Povoação",
    "lat": 37.7469,
    "lng": -25.2445999
  },
  {
    "id": "osm_5249572474",
    "name": "Paragem – Povoação",
    "lat": 37.7467388,
    "lng": -25.2447139
  },
  {
    "id": "osm_5250050415",
    "name": "Paragem – Povoação",
    "lat": 37.7487017,
    "lng": -25.2392489
  },
  {
    "id": "osm_5250409281",
    "name": "Paragem – Povoação",
    "lat": 37.749761,
    "lng": -25.2439374
  },
  {
    "id": "osm_5252189553",
    "name": "Paragem – Maia",
    "lat": 37.8173805,
    "lng": -25.4163042
  },
  {
    "id": "osm_5252189556",
    "name": "Paragem – Maia",
    "lat": 37.8163592,
    "lng": -25.4124981
  },
  {
    "id": "osm_5252288704",
    "name": "Paragem de Autocarro",
    "lat": 37.8507969,
    "lng": -25.1797875
  },
  {
    "id": "osm_5255730172",
    "name": "Ponta Delgada - Moaçor",
    "lat": 37.7431618,
    "lng": -25.6504422
  },
  {
    "id": "osm_5256762231",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7175104,
    "lng": -25.4186954
  },
  {
    "id": "osm_5257286499",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7178583,
    "lng": -25.3801131
  },
  {
    "id": "osm_5257286511",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7172579,
    "lng": -25.3837462
  },
  {
    "id": "osm_5257503822",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7158639,
    "lng": -25.3754796
  },
  {
    "id": "osm_5262216564",
    "name": "Lagoa - Escola",
    "lat": 37.74611,
    "lng": -25.5683881
  },
  {
    "id": "osm_5262216567",
    "name": "Lagoa - Escola",
    "lat": 37.7462584,
    "lng": -25.5686241
  },
  {
    "id": "osm_5262216581",
    "name": "Paragem – Lagoa",
    "lat": 37.7458247,
    "lng": -25.5667157
  },
  {
    "id": "osm_5262216584",
    "name": "Lagoa - Convento",
    "lat": 37.745672,
    "lng": -25.5623317
  },
  {
    "id": "osm_5262355963",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.746531,
    "lng": -25.5746122
  },
  {
    "id": "osm_5264076317",
    "name": "Lagoa - Senhora da Graça",
    "lat": 37.7453747,
    "lng": -25.5803734
  },
  {
    "id": "osm_5264151631",
    "name": "Lagoa - Alminhas",
    "lat": 37.7453825,
    "lng": -25.5832905
  },
  {
    "id": "osm_5265383321",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7466805,
    "lng": -25.5959592
  },
  {
    "id": "osm_5265383331",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7462482,
    "lng": -25.5935222
  },
  {
    "id": "osm_5265385627",
    "name": "Livramento - Estada Regional - Saida",
    "lat": 37.7468062,
    "lng": -25.6018669
  },
  {
    "id": "osm_5265413339",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7470414,
    "lng": -25.6041307
  },
  {
    "id": "osm_5265682856",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.751112,
    "lng": -25.6172306
  },
  {
    "id": "osm_5266871418",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7516464,
    "lng": -25.6259
  },
  {
    "id": "osm_5266908504",
    "name": "São Roque  - Corretora / Ilhéu",
    "lat": 37.7459243,
    "lng": -25.6373175
  },
  {
    "id": "osm_5267674938",
    "name": "Rua de São Gonçalo",
    "lat": 37.7487067,
    "lng": -25.6624674
  },
  {
    "id": "osm_5267675138",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7500526,
    "lng": -25.6594799
  },
  {
    "id": "osm_5267678294",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.748299,
    "lng": -25.6641496
  },
  {
    "id": "osm_5267824818",
    "name": "Rua Jose do Canto",
    "lat": 37.7465037,
    "lng": -25.6693168
  },
  {
    "id": "osm_5329145320",
    "name": "Paragem de Autocarro",
    "lat": 37.8354188,
    "lng": -25.1464378
  },
  {
    "id": "osm_5329181082",
    "name": "Paragem de Autocarro",
    "lat": 37.8318176,
    "lng": -25.1453386
  },
  {
    "id": "osm_5348978711",
    "name": "Paragem de Autocarro",
    "lat": 37.8120811,
    "lng": -25.1414426
  },
  {
    "id": "osm_5348988110",
    "name": "Paragem de Autocarro",
    "lat": 37.8087135,
    "lng": -25.1443424
  },
  {
    "id": "osm_5348990684",
    "name": "Paragem de Autocarro",
    "lat": 37.8101435,
    "lng": -25.1464621
  },
  {
    "id": "osm_5349005164",
    "name": "Paragem de Autocarro",
    "lat": 37.805042,
    "lng": -25.1458789
  },
  {
    "id": "osm_5548758026",
    "name": "Paragem – Furnas",
    "lat": 37.7692821,
    "lng": -25.3183761
  },
  {
    "id": "osm_5548759529",
    "name": "Paragem – Furnas",
    "lat": 37.7759871,
    "lng": -25.3135929
  },
  {
    "id": "osm_5951824678",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7167345,
    "lng": -25.4915484
  },
  {
    "id": "osm_5951824679",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7167871,
    "lng": -25.4908343
  },
  {
    "id": "osm_5951826088",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7199845,
    "lng": -25.4893167
  },
  {
    "id": "osm_6143209074",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7606614,
    "lng": -25.6634691
  },
  {
    "id": "osm_6143209075",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.761816,
    "lng": -25.6630089
  },
  {
    "id": "osm_6143209076",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7619147,
    "lng": -25.6630755
  },
  {
    "id": "osm_6143209077",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.757634,
    "lng": -25.6648495
  },
  {
    "id": "osm_6143209078",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7534367,
    "lng": -25.6664563
  },
  {
    "id": "osm_6143209079",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7502103,
    "lng": -25.6675853
  },
  {
    "id": "osm_6143209080",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7687245,
    "lng": -25.6602105
  },
  {
    "id": "osm_6143209081",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7688786,
    "lng": -25.6599869
  },
  {
    "id": "osm_6293093485",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7534208,
    "lng": -25.7223585
  },
  {
    "id": "osm_6440172958",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7194174,
    "lng": -25.458021
  },
  {
    "id": "osm_6788237299",
    "name": "Paragem de autocarro dos Poços",
    "lat": 37.8342387,
    "lng": -25.670084
  },
  {
    "id": "osm_7954579985",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7425609,
    "lng": -25.6571497
  },
  {
    "id": "osm_8804483817",
    "name": "Rua Arcanjo Lar",
    "lat": 37.7495378,
    "lng": -25.6781729
  },
  {
    "id": "osm_9152679526",
    "name": "Paragem – Praia do Pópulo",
    "lat": 37.7475443,
    "lng": -25.5849767
  },
  {
    "id": "osm_9152709838",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7177824,
    "lng": -25.4617141
  },
  {
    "id": "osm_9156627680",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7169799,
    "lng": -25.4443079
  },
  {
    "id": "osm_9826353566",
    "name": "Aerobus",
    "lat": 37.7490595,
    "lng": -25.7087486
  },
  {
    "id": "osm_10723575121",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7188806,
    "lng": -25.396643
  },
  {
    "id": "osm_10723575124",
    "name": "Paragem – Ribeira Chã",
    "lat": 37.7170473,
    "lng": -25.4726846
  },
  {
    "id": "osm_11196456947",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.718044,
    "lng": -25.4107949
  },
  {
    "id": "osm_11208941439",
    "name": "Paragem – Sete Cidades",
    "lat": 37.7997533,
    "lng": -25.7826385
  },
  {
    "id": "osm_11208941443",
    "name": "Paragem – Sete Cidades",
    "lat": 37.7974475,
    "lng": -25.7809867
  },
  {
    "id": "osm_11208941444",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8015751,
    "lng": -25.7837335
  },
  {
    "id": "osm_11208941445",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8028456,
    "lng": -25.7853799
  },
  {
    "id": "osm_11208941446",
    "name": "Paragem – Sete Cidades",
    "lat": 37.803466,
    "lng": -25.7900737
  },
  {
    "id": "osm_11208941456",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8073703,
    "lng": -25.8018608
  },
  {
    "id": "osm_11401342732",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7462433,
    "lng": -25.7010938
  },
  {
    "id": "osm_11401342733",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7460082,
    "lng": -25.7007169
  },
  {
    "id": "osm_11401436778",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7480731,
    "lng": -25.7055981
  },
  {
    "id": "osm_11972043740",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7708174,
    "lng": -25.6590733
  },
  {
    "id": "osm_11972043741",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7768786,
    "lng": -25.6569112
  },
  {
    "id": "osm_11972057353",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8205241,
    "lng": -25.6532007
  },
  {
    "id": "osm_11972065236",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7647588,
    "lng": -25.6625011
  },
  {
    "id": "osm_11972079283",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7673419,
    "lng": -25.6612564
  },
  {
    "id": "osm_11972079609",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7485712,
    "lng": -25.6656041
  },
  {
    "id": "osm_11972079610",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.826205,
    "lng": -25.6413539
  },
  {
    "id": "osm_11972081997",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.743184,
    "lng": -25.6815399
  },
  {
    "id": "osm_11972081998",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7722902,
    "lng": -25.6573154
  },
  {
    "id": "osm_11972085905",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7738493,
    "lng": -25.6566675
  },
  {
    "id": "osm_11972088447",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.735323,
    "lng": -25.6827982
  },
  {
    "id": "osm_11972089155",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8135395,
    "lng": -25.6705011
  },
  {
    "id": "osm_11972091398",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8201945,
    "lng": -25.6615935
  },
  {
    "id": "osm_11972091399",
    "name": "Paragem – Fenais da Luz",
    "lat": 37.8238287,
    "lng": -25.6493072
  },
  {
    "id": "osm_12003985638",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8626668,
    "lng": -25.7951318
  },
  {
    "id": "osm_12012917723",
    "name": "São Roque - Poço Velho",
    "lat": 37.7501496,
    "lng": -25.6317678
  },
  {
    "id": "osm_12015042282",
    "name": "Calhetas I. Largo Gonçalo Velho",
    "lat": 37.8224624,
    "lng": -25.6132155
  },
  {
    "id": "osm_12017222249",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8195735,
    "lng": -25.5268922
  },
  {
    "id": "osm_12018145217",
    "name": "Paragem – Ribeira Grande",
    "lat": 37.8260112,
    "lng": -25.5099504
  },
  {
    "id": "osm_12018145221",
    "name": "Paragem – Ribeira Grande",
    "lat": 37.8229579,
    "lng": -25.4306469
  },
  {
    "id": "osm_12018145230",
    "name": "Paragem – Ribeira Grande",
    "lat": 37.8260534,
    "lng": -25.5001809
  },
  {
    "id": "osm_12022480693",
    "name": "Paragem – Fajã de Baixo",
    "lat": 37.7501859,
    "lng": -25.6534598
  },
  {
    "id": "osm_12022984553",
    "name": "Paragem – Fajã de Cima",
    "lat": 37.7574169,
    "lng": -25.6649192
  },
  {
    "id": "osm_12025594569",
    "name": "Hop-on Hop-off Shuttle Service",
    "lat": 37.7848433,
    "lng": -25.5014142
  },
  {
    "id": "osm_12029134850",
    "name": "Paragem – Rabo de Peixe",
    "lat": 37.8134083,
    "lng": -25.5774604
  },
  {
    "id": "osm_12035571050",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.7193027,
    "lng": -25.455294
  },
  {
    "id": "osm_12035571067",
    "name": "Ponta Delgada - Rua da Boa Nova",
    "lat": 37.7423569,
    "lng": -25.6551788
  },
  {
    "id": "osm_12040233964",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8050716,
    "lng": -25.7990704
  },
  {
    "id": "osm_12040271478",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8031597,
    "lng": -25.7928629
  },
  {
    "id": "osm_12040271493",
    "name": "Ginetes",
    "lat": 37.8474349,
    "lng": -25.8377525
  },
  {
    "id": "osm_12040271517",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8035287,
    "lng": -25.7885543
  },
  {
    "id": "osm_12041362105",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8381589,
    "lng": -25.8319797
  },
  {
    "id": "osm_12041362106",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8262025,
    "lng": -25.8223963
  },
  {
    "id": "osm_12041362107",
    "name": "Paragem – Sete Cidades",
    "lat": 37.8231713,
    "lng": -25.8215764
  },
  {
    "id": "osm_12041362108",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7514401,
    "lng": -25.7124058
  },
  {
    "id": "osm_12041653205",
    "name": "Paragem – Santo António",
    "lat": 37.8670131,
    "lng": -25.7097055
  },
  {
    "id": "osm_12041653206",
    "name": "Paragem – Capelas",
    "lat": 37.8294545,
    "lng": -25.6722833
  },
  {
    "id": "osm_12041653207",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7410869,
    "lng": -25.6871059
  },
  {
    "id": "osm_12041653208",
    "name": "Paragem – Ponta Delgada",
    "lat": 37.7375412,
    "lng": -25.6824465
  },
  {
    "id": "osm_12043347947",
    "name": "Paragem – Furnas",
    "lat": 37.7727688,
    "lng": -25.3162529
  },
  {
    "id": "osm_12043526795",
    "name": "São Roque - Largo da Madalena",
    "lat": 37.7474549,
    "lng": -25.635218
  },
  {
    "id": "osm_12043526796",
    "name": "São Roque - Junta Frequesia",
    "lat": 37.7484478,
    "lng": -25.6339576
  },
  {
    "id": "osm_12043526797",
    "name": "Atalhada - Igreja",
    "lat": 37.7450935,
    "lng": -25.58909
  },
  {
    "id": "osm_12043526798",
    "name": "Paragem – Lagoa",
    "lat": 37.7342983,
    "lng": -25.5453066
  },
  {
    "id": "osm_12043526799",
    "name": "Paragem – Lagoa",
    "lat": 37.7252466,
    "lng": -25.535719
  },
  {
    "id": "osm_12334727112",
    "name": "Paragem – Ramal Mosteiros",
    "lat": 37.8475801,
    "lng": -25.8378321
  },
  {
    "id": "osm_12359863066",
    "name": "Ribeira Grande - Jardim",
    "lat": 37.8222101,
    "lng": -25.5199238
  },
  {
    "id": "osm_13168005466",
    "name": "Praça Vasco da Gama",
    "lat": 37.7385096,
    "lng": -25.6701208
  },
  {
    "id": "osm_13168023088",
    "name": "Rua Coronel Silva Leal",
    "lat": 37.7406955,
    "lng": -25.6722602
  },
  {
    "id": "osm_13168023089",
    "name": "Largo de Colégio",
    "lat": 37.743264,
    "lng": -25.6698888
  },
  {
    "id": "osm_13168027776",
    "name": "Praça Vasco da Gama",
    "lat": 37.7378808,
    "lng": -25.6700623
  },
  {
    "id": "osm_13168028286",
    "name": "Av. Infante D. Henrique",
    "lat": 37.7372202,
    "lng": -25.6720711
  },
  {
    "id": "osm_13168028657",
    "name": "Rua Margarida de Chaves",
    "lat": 37.7438606,
    "lng": -25.6650078
  },
  {
    "id": "osm_13168035414",
    "name": "Rua De São Gonçalo",
    "lat": 37.7481924,
    "lng": -25.6640607
  },
  {
    "id": "osm_13168038374",
    "name": "Rua Teófilo de Braga",
    "lat": 37.7365496,
    "lng": -25.6739706
  },
  {
    "id": "osm_13168040427",
    "name": "Rua Manuel Augusto Amaral",
    "lat": 37.7432799,
    "lng": -25.6733552
  },
  {
    "id": "osm_13168043945",
    "name": "Rua Mão de Deus",
    "lat": 37.7446241,
    "lng": -25.6606142
  },
  {
    "id": "osm_13168044071",
    "name": "Rua Dr. Hugo Moreiro",
    "lat": 37.7456558,
    "lng": -25.6580792
  },
  {
    "id": "osm_13168045621",
    "name": "Rua Dr. Hugo Moreiro",
    "lat": 37.7490605,
    "lng": -25.6588842
  },
  {
    "id": "osm_13168432727",
    "name": "Praça Vasco da Gama",
    "lat": 37.7383029,
    "lng": -25.6700183
  },
  {
    "id": "osm_13168432728",
    "name": "Praça Vasco da Gama",
    "lat": 37.7383461,
    "lng": -25.6700126
  },
  {
    "id": "osm_14079352196",
    "name": "Paragem – Vila Franca do Campo",
    "lat": 37.716302,
    "lng": -25.4402916
  }
];
